name: Shopkeepers
version: '1.25'
description: Custom villager shopkeepers
author: nisovin
website: http://dev.bukkit.org/server-mods/shopkeepers/
softdepend: [Multiverse-Core, My Worlds, Transporter, Citizens]

main: com.nisovin.shopkeepers.ShopkeepersPlugin

commands:
    shopkeeper:
        description: Test
        aliases: [shopkeepers]
        
permissions:
    shopkeeper.trade:
        description: Trade with shopkeepers
        default: true
    shopkeeper.reload:
        description: Reloads the plugin
        default: op
    shopkeeper.bypass:
        description: Bypass player shop restrictions
        default: op
    shopkeeper.purchase:
        description: Purchase items from any shopkeeper
        default: true
    shopkeeper.transfer:
        description: Transfer ownership of a shopkeeper
        default: op
    shopkeeper.setforhire:
        description: Set a shopkeeper to be for hire
        default: op
    shopkeeper.hire:
        description: Hire a shopkeeper
        default: true
    shopkeeper.remote:
        description: Trade with a remote admin shop by name
        default: false
        
    shopkeeper.admin:
        description: Create and modify an admin shopkeeper
        default: op
    shopkeeper.player:
        description: Create and modify any player shopkeeper
        default: false
        children:
            shopkeeper.player.normal: true
            shopkeeper.player.book: true
            shopkeeper.player.buy: true
            shopkeeper.player.trade: true
    shopkeeper.player.normal:
        description: Create and modify a normal player shopkeeper
        default: true
    shopkeeper.player.book:
        description: Create and modify a book player shopkeeper
        default: true
    shopkeeper.player.buy:
        description: Create and modify a buying player shopkeeper
        default: true
    shopkeeper.player.trade:
        description: Create and modify a trading player shopkeeper
        default: true

    shopkeeper.sign:
        description: Create sign shopkeepers
        default: true
    shopkeeper.citizen:
        description: Create citizens shopkeepers
        default: op
    shopkeeper.entity.*:
        description: Create shopkeepers of all entity types
        default: op

    shopkeeper.villager:
        description: Create a villager shopkeeper
        default: true
        children:
            shopkeeper.entity.villager: true
    shopkeeper.witch:
        description: Create a witch shopkeeper
        default: true
        children:
            shopkeeper.entity.witch: true
    shopkeeper.creeper:
        description: Create a creeper shopkeeper
        default: true
        children:
            shopkeeper.entity.creeper: true
